default_stages: [commit]
exclude: ^test/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: pretty-format-json
        name: Format json files
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py39]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.276
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --line-length=120]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--check, --line-length=120]

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
